"""empty message

Revision ID: 5195eafb19e9
Revises: 355cf6637f85
Create Date: 2023-06-08 17:07:19.787660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5195eafb19e9'
down_revision = '355cf6637f85'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
