# Service
apiVersion: v1
kind: Service
metadata:
  name: backend
  # annotations:
  #   metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: backend
  ports:
    - protocol: 'TCP'
      port: 8000
      targetPort: 8000
  type: LoadBalancer
  # loadBalancerIP: MINIKUBE_IP
  # externalIPs:
  # - "MINIKUBE_IP"

---

# deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: back
          imagePullPolicy: Never
          ports:
            - containerPort: 8000

