# Service
apiVersion: v1
kind: Service
metadata:
  name: frontend
  # annotations:
  #   metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: frontend
  ports:
    - protocol: 'TCP'
      port: 5173
      targetPort: 5173
  type: LoadBalancer
  # loadBalancerIP: MINIKUBE_IP
  # externalIPs:
  # - "MINIKUBE_IP"

---

# deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: front
          imagePullPolicy: Never
          ports:
            - containerPort: 5173
