"""empty message

Revision ID: 2ed90e42a77e
Revises: e84d8db8d8f5
Create Date: 2023-06-15 09:13:23.829505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ed90e42a77e'
down_revision = 'e84d8db8d8f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
