"""empty message

Revision ID: b4ea00f7ccd9
Revises: c8fa8af978e2
Create Date: 2023-06-09 08:34:32.620076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4ea00f7ccd9'
down_revision = 'c8fa8af978e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modeify_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modeify_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('modeify_date')

    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_column('modeify_date')

    # ### end Alembic commands ###
