"""empty message

Revision ID: c8fa8af978e2
Revises: 5195eafb19e9
Create Date: 2023-06-08 17:13:16.632203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8fa8af978e2'
down_revision = '5195eafb19e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
