"""empty message

Revision ID: e84d8db8d8f5
Revises: b4ea00f7ccd9
Create Date: 2023-06-09 09:49:14.581320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e84d8db8d8f5'
down_revision = 'b4ea00f7ccd9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
